--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockHorizons/PerWorldInventory
branches:
  - master
projects:
  PerWorldInventory:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
...
