---
name: PerWorldInventory
version: 1.0.0
api: 3.0.0
main: BlockHorizons\PerWorldInventory\PerWorldInventory
author: BlockHorizons

permissions:
  per-world-inventory.bypass:
    default: false
    description: Allows bypassing the per world inventory.

commands:
  pwi:
    default: op
...
